#!/bin/bash
#
mkdir genos-temp && cd genos-temp
#
# Night Theme Switcher:
git clone https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension.git && cd nightthemeswitcher-gnome-shell-extension
make build && make install
gnome-extensions enable nightthemeswitcher@romainvigier.fr
cd ..
#
# Blyr:
git clone https://github.com/yozoon/gnome-shell-extension-blyr.git && cd gnome-shell-extension-blyr
make local-install
cd ..
#
# Caffeine:
git clone git://github.com/eonpatapon/gnome-shell-extension-caffeine.git && cd gnome-shell-extension-caffeine
./update-locale.sh
glib-compile-schemas --strict --targetdir=caffeine@patapon.info/schemas/ caffeine@patapon.info/schemas
cp -r caffeine@patapon.info ~/.local/share/gnome-shell/extensions
cd ..
#
cd ..
rm -r genos-temp
#
