#!/bin/bash
#
# Modifies Dash to Dock settings:
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed true
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
gsettings set org.gnome.shell.extensions.dash-to-dock require-pressure-to-show false
gsettings set org.gnome.shell.extensions.dash-to-dock running-indicator-style 'DOTS'
#gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-customize-running-dots true
#gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-color '#ffffff'
#gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-color '#ffffff'
gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false
gsettings set org.gnome.shell.extensions.dash-to-dock custom-background-color true
gsettings set org.gnome.shell.extensions.dash-to-dock background-color '#000000'
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'FIXED'
gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity '0.8'
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize-or-previews'
gsettings set org.gnome.shell.extensions.dash-to-dock shift-click-action 'launch'
gsettings set org.gnome.shell.extensions.dash-to-dock middle-click-action 'cycle-windows'
gsettings set org.gnome.shell.extensions.dash-to-dock shift-middle-click-action 'quit'
#
# Modifies Dash to Panel settings:
gsettings set org.gnome.shell.extensions.dash-to-panel dot-style-focused 'CILIORA'
gsettings set org.gnome.shell.extensions.dash-to-panel dot-style-unfocused 'CILIORA'
gsettings set org.gnome.shell.extensions.dash-to-panel trans-use-custom-opacity true
gsettings set org.gnome.shell.extensions.dash-to-panel trans-use-dynamic-opacity true
gsettings set org.gnome.shell.extensions.dash-to-panel trans-panel-opacity '0,7'
gsettings set org.gnome.shell.extensions.dash-to-panel trans-dynamic-anim-target '1'
gsettings set org.gnome.shell.extensions.dash-to-panel hot-keys true
gsettings set org.gnome.shell.extensions.dash-to-panel shift-click-action 'launch'
gsettings set org.gnome.shell.extensions.dash-to-panel middle-click-action 'cycle'
gsettings set org.gnome.shell.extensions.dash-to-panel shift-middle-click-action 'quit'
#
# Modifies Blyr settings:
gsettings set org.gnome.shell.extensions.blyr activities-brightness '0.6'
gsettings set org.gnome.shell.extensions.blyr intensity '15'
gsettings set org.gnome.shell.extensions.blyr mode '2'
gsettings set org.gnome.shell.extensions.blyr panelbrightness '1'
#
# Modifies Tilix settings:
gsettings set com.gexperts.Tilix close-with-last-session false
gsettings set com.gexperts.Tilix control-click-titlebar true
gsettings set com.gexperts.Tilix enable-wide-handle true
gsettings set com.gexperts.Tilix tab-position 'top'
gsettings set com.gexperts.Tilix terminal-title-show-when-single false
gsettings set com.gexperts.Tilix theme-variant 'dark'
gsettings set com.gexperts.Tilix use-overlay-scrollbar true
#
# Modifies gthumb settings:
gsettings set org.gnome.gthumb.browser thumbnail-size '200'
gsettings set org.gnome.gthumb.browser maximized true
#
# Modifies Lollypop settings:
gsettings set org.gnome.Lollypop dark-ui true
#
# Modifies Desktop interface settings:
gsettings set org.gnome.desktop.interface icon-theme 'Elementary'
gsettings set org.gnome.desktop.interface cursor-theme 'Yaru'
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface enable-hot-corners false
#
# Modifies touchpad settings:
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad disable-while-typing false
#
# Modifies Nautilus settings:
gsettings set org.gnome.nautilus.preferences show-create-link true
gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'
#
# Modifies power settings:
gsettings set org.gnome.settings-daemon.plugins.power critical-battery-action 'suspend'
gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'
#
# Modifies enabled GNOME Shell Extensions:
gsettings set org.gnome.shell enabled-extensions "['nightthemeswitcher@romainvigier.fr', 'blyr@yozoon.dev.gmail.com', 'caffeine@patapon.info', 'gsconnect@andyholmes.github.io', 'bluetooth-quick-connect@bjarosze.gmail.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'desktop-icons@csoriano', 'appindicatorsupport@rgcjonas.gmail.com']"
#
# Modifies default GNOME Shell Favorites:
gsettings set org.gnome.shell favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.gedit.desktop', 'org.gnome.Geary.desktop', 'org.gnome.Calendar.desktop', 'gnome-control-center.desktop', 'org.gnome.Software.desktop', 'yelp.desktop']"
#
# Modifies window buttons:
gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
#
# Modifies default desktop background:
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/gnome/ColdWarm.jpg'
#
# Modifies antialiasing:
gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'
#
# Enable TLP:
systemctl enable tlp
#
