#!/bin/bash
#
chmod +x ./modules/*
#
sudo ./modules/pkg-managers
#sudo ./modules/systd-boot
sudo ./modules/pkgs-rm
sudo ./modules/pkgs
./modules/extensions
sudo ./modules/syst-config
sudo ./modules/third-party-repos
./modules/flatpak
#
